# Test against this version of Node.js
environment:
  matrix:
    # node.js
    - nodejs_version: "stable"
    - nodejs_version: "6"
    - nodejs_version: "4"
    - nodejs_version: "0.12"

# Install scripts. (runs after repo cloning)
install:
  - where git
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - node -e "console.log(process.env)"
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # run tests
  - "npm run test"

# Don't actually build.
build: off
