version: "{build}"
skip_branch_with_pr: true
skip_tags: true
build: off

environment:
  matrix:
    - nodejs_version: stable
    - nodejs_version: lts

# Install scripts. (runs after repo cloning)
install:
  # install Node.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm i
  - bash -c "cd node_modules/nyc && npm i https://github.com/pangrr/spawn-wrap/archive/fix/shebang-path-space.tar.gz"


# to run your custom scripts instead of automatic tests
test_script:
  # - setx Path "node_modules\.bin;%Path%"
  - npm test

# to run your custom scripts instead of provider deployments
after_test:
  - npm run report-coverage
